/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlfabetoRouteImport } from './routes/alfabeto'
import { Route as FlashcardsRouteImport } from './routes/flashcards'
import { Route as GramaticaRouteImport } from './routes/gramatica'
import { Route as LexicoRouteImport } from './routes/lexico'
import { Route as OikosRouteImport } from './routes/oikos'
import { Route as ParadigmasRouteImport } from './routes/paradigmas'
import { Route as TreinoRouteImport } from './routes/treino'
import { Route as CapituloIdRouteImport } from './routes/capitulo.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlfabetoRoute = AlfabetoRouteImport.update({
  id: '/alfabeto',
  path: '/alfabeto',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardsRoute = FlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => rootRouteImport,
} as any)
const GramaticaRoute = GramaticaRouteImport.update({
  id: '/gramatica',
  path: '/gramatica',
  getParentRoute: () => rootRouteImport,
} as any)
const LexicoRoute = LexicoRouteImport.update({
  id: '/lexico',
  path: '/lexico',
  getParentRoute: () => rootRouteImport,
} as any)
const OikosRoute = OikosRouteImport.update({
  id: '/oikos',
  path: '/oikos',
  getParentRoute: () => rootRouteImport,
} as any)
const ParadigmasRoute = ParadigmasRouteImport.update({
  id: '/paradigmas',
  path: '/paradigmas',
  getParentRoute: () => rootRouteImport,
} as any)
const TreinoRoute = TreinoRouteImport.update({
  id: '/treino',
  path: '/treino',
  getParentRoute: () => rootRouteImport,
} as any)
const CapituloIdRoute = CapituloIdRouteImport.update({
  id: '/capitulo/$id',
  path: '/capitulo/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alfabeto': typeof AlfabetoRoute
  '/flashcards': typeof FlashcardsRoute
  '/gramatica': typeof GramaticaRoute
  '/lexico': typeof LexicoRoute
  '/oikos': typeof OikosRoute
  '/paradigmas': typeof ParadigmasRoute
  '/treino': typeof TreinoRoute
  '/capitulo/$id': typeof CapituloIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alfabeto': typeof AlfabetoRoute
  '/flashcards': typeof FlashcardsRoute
  '/gramatica': typeof GramaticaRoute
  '/lexico': typeof LexicoRoute
  '/oikos': typeof OikosRoute
  '/paradigmas': typeof ParadigmasRoute
  '/treino': typeof TreinoRoute
  '/capitulo/$id': typeof CapituloIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alfabeto': typeof AlfabetoRoute
  '/flashcards': typeof FlashcardsRoute
  '/gramatica': typeof GramaticaRoute
  '/lexico': typeof LexicoRoute
  '/oikos': typeof OikosRoute
  '/paradigmas': typeof ParadigmasRoute
  '/treino': typeof TreinoRoute
  '/capitulo/$id': typeof CapituloIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alfabeto'
    | '/flashcards'
    | '/gramatica'
    | '/lexico'
    | '/oikos'
    | '/paradigmas'
    | '/treino'
    | '/capitulo/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alfabeto'
    | '/flashcards'
    | '/gramatica'
    | '/lexico'
    | '/oikos'
    | '/paradigmas'
    | '/treino'
    | '/capitulo/$id'
  id:
    | '__root__'
    | '/'
    | '/alfabeto'
    | '/flashcards'
    | '/gramatica'
    | '/lexico'
    | '/oikos'
    | '/paradigmas'
    | '/treino'
    | '/capitulo/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlfabetoRoute: typeof AlfabetoRoute
  FlashcardsRoute: typeof FlashcardsRoute
  GramaticaRoute: typeof GramaticaRoute
  LexicoRoute: typeof LexicoRoute
  OikosRoute: typeof OikosRoute
  ParadigmasRoute: typeof ParadigmasRoute
  TreinoRoute: typeof TreinoRoute
  CapituloIdRoute: typeof CapituloIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alfabeto': {
      id: '/alfabeto'
      path: '/alfabeto'
      fullPath: '/alfabeto'
      preLoaderRoute: typeof AlfabetoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcards': {
      id: '/flashcards'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof FlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gramatica': {
      id: '/gramatica'
      path: '/gramatica'
      fullPath: '/gramatica'
      preLoaderRoute: typeof GramaticaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lexico': {
      id: '/lexico'
      path: '/lexico'
      fullPath: '/lexico'
      preLoaderRoute: typeof LexicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oikos': {
      id: '/oikos'
      path: '/oikos'
      fullPath: '/oikos'
      preLoaderRoute: typeof OikosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paradigmas': {
      id: '/paradigmas'
      path: '/paradigmas'
      fullPath: '/paradigmas'
      preLoaderRoute: typeof ParadigmasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treino': {
      id: '/treino'
      path: '/treino'
      fullPath: '/treino'
      preLoaderRoute: typeof TreinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capitulo/$id': {
      id: '/capitulo/$id'
      path: '/capitulo/$id'
      fullPath: '/capitulo/$id'
      preLoaderRoute: typeof CapituloIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlfabetoRoute: AlfabetoRoute,
  FlashcardsRoute: FlashcardsRoute,
  GramaticaRoute: GramaticaRoute,
  LexicoRoute: LexicoRoute,
  OikosRoute: OikosRoute,
  ParadigmasRoute: ParadigmasRoute,
  TreinoRoute: TreinoRoute,
  CapituloIdRoute: CapituloIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
